# Generated by Django 3.0 on 2024-11-12 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'エリア1',
                'db_table': 'Area1',
            },
        ),
        migrations.CreateModel(
            name='Area2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('area1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area2_area1', to='CCapp.Area1', verbose_name='エリア1')),
            ],
            options={
                'verbose_name': 'エリア2',
                'db_table': 'Area2',
            },
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'カテゴリ1',
                'db_table': 'Category1',
            },
        ),
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2_category1', to='CCapp.Category1', verbose_name='カテゴリ1')),
            ],
            options={
                'verbose_name': 'カテゴリ2',
                'db_table': 'Category2',
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corp', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='法人番号')),
                ('cName', models.CharField(max_length=255, verbose_name='法人名')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('cMail', models.CharField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('cTel', models.CharField(max_length=15, verbose_name='電話番号')),
                ('url', models.URLField(max_length=511, verbose_name='URL')),
            ],
            options={
                'verbose_name': '法人',
                'db_table': 'corporation',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'タグ',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('mail', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=255, verbose_name='パスワード')),
                ('authority', models.IntegerField(verbose_name='権限')),
            ],
            options={
                'verbose_name': 'ユーザ',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CCapp.User', verbose_name='ユーザID')),
                ('QA_l', models.TextField(verbose_name='自己分析リスト')),
            ],
            options={
                'verbose_name': '自己分析',
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='SupportDM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('read', models.BooleanField(default=False, verbose_name='既読')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('userReceive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportDM_receive', to='CCapp.User', verbose_name='受信者ID')),
                ('userSend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportDM_send', to='CCapp.User', verbose_name='送信者ID')),
            ],
            options={
                'verbose_name': 'サポートDM',
                'db_table': 'supportDM',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('solicitation', models.TextField(verbose_name='募集要項')),
                ('course', models.CharField(max_length=255, verbose_name='コース名')),
                ('forms', models.CharField(max_length=31, verbose_name='雇用形態')),
                ('roles', models.CharField(max_length=255, verbose_name='配属職種')),
                ('CoB', models.TextField(verbose_name='提出書類')),
                ('subject', models.CharField(max_length=255, verbose_name='募集対象')),
                ('NoP', models.CharField(max_length=63, verbose_name='募集人数')),
                ('departments', models.CharField(max_length=255, verbose_name='募集学部・学科')),
                ('characteristic', models.TextField(verbose_name='募集特徴')),
                ('PES', models.TextField(verbose_name='採用後の対応')),
                ('giving', models.CharField(max_length=255, verbose_name='初任給')),
                ('allowances', models.CharField(max_length=255, verbose_name='諸手当')),
                ('salaryRaise', models.CharField(max_length=63, verbose_name='昇給')),
                ('bonus', models.CharField(max_length=31, verbose_name='賞与')),
                ('holiday', models.TextField(verbose_name='休日休暇')),
                ('welfare', models.TextField(verbose_name='福利厚生')),
                ('workingHours', models.CharField(max_length=255, verbose_name='勤務時間')),
                ('tag_l', models.TextField(verbose_name='タグリスト')),
                ('user_l', models.TextField(verbose_name='応募者リスト')),
                ('period', models.DateTimeField(verbose_name='公開期限')),
                ('status', models.BooleanField(default=False, verbose_name='公開状況')),
                ('area2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_area2', to='CCapp.Area2', verbose_name='エリア2')),
                ('category1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_category1', to='CCapp.Category1', verbose_name='カテゴリ1')),
                ('category2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_category2', to='CCapp.Category2', verbose_name='カテゴリ2')),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCapp.Corporation', verbose_name='法人')),
            ],
            options={
                'verbose_name': '求人',
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名前')),
                ('read', models.BooleanField(default=False, verbose_name='既読')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCapp.Corporation', verbose_name='法人番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCapp.User', verbose_name='ユーザID')),
            ],
            options={
                'verbose_name': 'DM',
                'db_table': 'DM',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='CCapp.User', verbose_name='ユーザID')),
                ('nationality', models.CharField(max_length=255, verbose_name='国籍')),
                ('birth', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(max_length=15, verbose_name='性別')),
                ('graduation', models.IntegerField(verbose_name='卒業年度')),
                ('uSchool', models.CharField(max_length=255, verbose_name='学校名')),
                ('sClass', models.IntegerField(verbose_name='学校区分')),
                ('sol', models.IntegerField(verbose_name='文理区分')),
                ('department', models.CharField(max_length=31, verbose_name='学科名')),
                ('uTel', models.CharField(max_length=15, verbose_name='電話番号')),
                ('uAddress', models.CharField(max_length=255, verbose_name='住所')),
                ('uOffer', models.CharField(max_length=255, verbose_name='内定先')),
                ('jOffer_l', models.CharField(max_length=255, verbose_name='応募求人リスト')),
                ('area1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_area1', to='CCapp.Area1', verbose_name='エリア1')),
                ('category1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_category1', to='CCapp.Category1', verbose_name='カテゴリ1')),
                ('category2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_category2', to='CCapp.Category2', verbose_name='カテゴリ2')),
            ],
            options={
                'verbose_name': 'プロフィール',
                'db_table': 'profile',
            },
        ),
    ]
