# Generated by Django 5.1.3 on 2024-11-29 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area0',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'エリア0',
                'db_table': 'Area0',
            },
        ),
        migrations.CreateModel(
            name='Category00',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'カテゴリ00',
                'db_table': 'Category00',
            },
        ),
        migrations.CreateModel(
            name='Category10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'カテゴリ10',
                'db_table': 'Category10',
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corp', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='法人番号')),
                ('name', models.CharField(max_length=256, verbose_name='法人名')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
                ('cMail', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('cTel', models.CharField(max_length=16, verbose_name='電話番号')),
                ('url', models.URLField(max_length=512, verbose_name='URL')),
            ],
            options={
                'verbose_name': '法人',
                'db_table': 'corporation',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('mail', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='名前')),
                ('authority', models.IntegerField(choices=[(0, 'Admin'), (1, 'Support Staff'), (2, 'Service User')], default=2, verbose_name='権限')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Question00',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': '質問00',
                'db_table': 'question00',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'タグ',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='Area1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('area0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area1_area0', to='CCapp.area0', verbose_name='エリア0')),
            ],
            options={
                'verbose_name': 'エリア1',
                'db_table': 'Area1',
            },
        ),
        migrations.CreateModel(
            name='Area2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('area1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area2_area1', to='CCapp.area1', verbose_name='エリア1')),
            ],
            options={
                'verbose_name': 'エリア2',
                'db_table': 'Area2',
            },
        ),
        migrations.CreateModel(
            name='Category01',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('category00', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category01_category00', to='CCapp.category00', verbose_name='カテゴリ00')),
            ],
            options={
                'verbose_name': 'カテゴリ01',
                'db_table': 'Category01',
            },
        ),
        migrations.CreateModel(
            name='Category11',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('category10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category11_category10', to='CCapp.category10', verbose_name='カテゴリ10')),
            ],
            options={
                'verbose_name': 'カテゴリ11',
                'db_table': 'Category11',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='求人名')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('solicitation', models.TextField(verbose_name='募集要項')),
                ('course', models.CharField(max_length=256, verbose_name='コース名')),
                ('forms', models.CharField(max_length=32, verbose_name='雇用形態')),
                ('roles', models.CharField(max_length=256, verbose_name='配属職種')),
                ('CoB', models.TextField(verbose_name='提出書類')),
                ('subject', models.CharField(max_length=256, verbose_name='募集対象')),
                ('NoP', models.CharField(max_length=64, verbose_name='募集人数')),
                ('departments', models.CharField(max_length=256, verbose_name='募集学部・学科')),
                ('characteristic', models.TextField(verbose_name='募集特徴')),
                ('PES', models.TextField(verbose_name='採用後の対応')),
                ('giving', models.CharField(max_length=256, verbose_name='初任給')),
                ('allowances', models.CharField(max_length=256, verbose_name='諸手当')),
                ('salaryRaise', models.CharField(max_length=64, verbose_name='昇給')),
                ('bonus', models.CharField(max_length=32, verbose_name='賞与')),
                ('holiday', models.TextField(verbose_name='休日休暇')),
                ('workingHours', models.CharField(max_length=256, verbose_name='勤務時間')),
                ('period', models.DateTimeField(db_index=True, verbose_name='公開期限')),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='公開状況')),
                ('area1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_area1', to='CCapp.area1', verbose_name='エリア1')),
                ('category00', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category00', verbose_name='カテゴリ00')),
                ('category01', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category01', verbose_name='カテゴリ01')),
                ('category10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category10', verbose_name='カテゴリ10')),
                ('category11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category11', verbose_name='カテゴリ11')),
                ('corporation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CCapp.corporation', verbose_name='法人')),
            ],
            options={
                'verbose_name': '求人',
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='OfferEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True, verbose_name='応募日')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerApp_offer', to='CCapp.offer', verbose_name='求人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerApp_user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '求人応募',
                'db_table': 'offer_entry',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='applicants',
            field=models.ManyToManyField(related_name='offer_offerEntry', through='CCapp.OfferEntry', to=settings.AUTH_USER_MODEL, verbose_name='応募者リスト'),
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('read', models.BooleanField(default=False, verbose_name='既読')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCapp.corporation', verbose_name='法人番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
            ],
            options={
                'verbose_name': 'DM',
                'db_table': 'DM',
            },
        ),
        migrations.CreateModel(
            name='Question01',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('question00', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question01_question00', to='CCapp.question00', verbose_name='質問00')),
            ],
            options={
                'verbose_name': '質問01',
                'db_table': 'question01',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='回答')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
                ('question01', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_question01', to='CCapp.question01', verbose_name='質問')),
            ],
            options={
                'verbose_name': '自己分析',
                'db_table': 'assessment',
            },
        ),
        migrations.CreateModel(
            name='SupportDM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('read', models.BooleanField(default=False, verbose_name='既読')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('userReceive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportDM_receive', to=settings.AUTH_USER_MODEL, verbose_name='受信者ID')),
                ('userSend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportDM_send', to=settings.AUTH_USER_MODEL, verbose_name='送信者ID')),
            ],
            options={
                'verbose_name': 'サポートDM',
                'db_table': 'supportDM',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='welfare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.tag', verbose_name='福利厚生'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='ユーザID')),
                ('furigana', models.CharField(max_length=256, verbose_name='フリガナ')),
                ('nationality', models.CharField(max_length=256, verbose_name='国籍')),
                ('birth', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(max_length=16, verbose_name='性別')),
                ('graduation', models.IntegerField(verbose_name='卒業年度')),
                ('uSchool', models.CharField(max_length=256, verbose_name='学校名')),
                ('sClass', models.IntegerField(verbose_name='学校区分')),
                ('sol', models.IntegerField(verbose_name='文理区分')),
                ('department', models.CharField(max_length=32, verbose_name='学科名')),
                ('uTel', models.CharField(max_length=16, verbose_name='電話番号')),
                ('postalCode', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('uAddress', models.CharField(max_length=256, verbose_name='住所')),
                ('uOffer', models.CharField(max_length=256, verbose_name='内定先')),
                ('area1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.area1', verbose_name='エリア1')),
                ('category00', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category00', verbose_name='カテゴリ00')),
                ('category01', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category01', verbose_name='カテゴリ01')),
                ('category10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category10', verbose_name='カテゴリ10')),
                ('category11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.category11', verbose_name='カテゴリ11')),
            ],
            options={
                'verbose_name': 'プロフィール',
                'db_table': 'profile',
            },
        ),
        migrations.AddIndex(
            model_name='offerentry',
            index=models.Index(fields=['offer', 'user'], name='offer_entry_offer_i_68cd6d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerentry',
            unique_together={('offer', 'user')},
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', 'period'], name='offer_status_0d44c8_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['area1', 'category00', 'category10'], name='offer_area1_i_93489e_idx'),
        ),
    ]
