# Generated by Django 3.0 on 2024-11-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area0',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'エリア0',
                'db_table': 'Area0',
            },
        ),
        migrations.CreateModel(
            name='Area1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('area0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area1_area0', to='CCapp.Area0', verbose_name='エリア0')),
            ],
            options={
                'verbose_name': 'エリア1',
                'db_table': 'Area1',
            },
        ),
        migrations.CreateModel(
            name='Category00',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'カテゴリ00',
                'db_table': 'Category00',
            },
        ),
        migrations.CreateModel(
            name='Category01',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('category00', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category01_category00', to='CCapp.Category00', verbose_name='カテゴリ00')),
            ],
            options={
                'verbose_name': 'カテゴリ01',
                'db_table': 'Category01',
            },
        ),
        migrations.CreateModel(
            name='Category10',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'カテゴリ10',
                'db_table': 'Category10',
            },
        ),
        migrations.CreateModel(
            name='Category11',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('category10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category11_category10', to='CCapp.Category10', verbose_name='カテゴリ10')),
            ],
            options={
                'verbose_name': 'カテゴリ11',
                'db_table': 'Category11',
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('corp', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='法人番号')),
                ('name', models.CharField(max_length=256, verbose_name='法人名')),
                ('address', models.CharField(max_length=256, verbose_name='住所')),
                ('cMail', models.CharField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('cTel', models.CharField(max_length=16, verbose_name='電話番号')),
                ('url', models.URLField(max_length=512, verbose_name='URL')),
            ],
            options={
                'verbose_name': '法人',
                'db_table': 'corporation',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('solicitation', models.TextField(verbose_name='募集要項')),
                ('course', models.CharField(max_length=256, verbose_name='コース名')),
                ('forms', models.CharField(max_length=32, verbose_name='雇用形態')),
                ('roles', models.CharField(max_length=256, verbose_name='配属職種')),
                ('CoB', models.TextField(verbose_name='提出書類')),
                ('subject', models.CharField(max_length=256, verbose_name='募集対象')),
                ('NoP', models.CharField(max_length=64, verbose_name='募集人数')),
                ('departments', models.CharField(max_length=256, verbose_name='募集学部・学科')),
                ('characteristic', models.TextField(verbose_name='募集特徴')),
                ('PES', models.TextField(verbose_name='採用後の対応')),
                ('giving', models.CharField(max_length=256, verbose_name='初任給')),
                ('allowances', models.CharField(max_length=256, verbose_name='諸手当')),
                ('salaryRaise', models.CharField(max_length=64, verbose_name='昇給')),
                ('bonus', models.CharField(max_length=32, verbose_name='賞与')),
                ('holiday', models.TextField(verbose_name='休日休暇')),
                ('workingHours', models.CharField(max_length=256, verbose_name='勤務時間')),
                ('period', models.DateTimeField(verbose_name='公開期限')),
                ('status', models.BooleanField(default=False, verbose_name='公開状況')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question00',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': '質問00',
                'db_table': 'question00',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'タグ',
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('mail', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
                ('authority', models.IntegerField(verbose_name='権限')),
            ],
            options={
                'verbose_name': 'ユーザ',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='SupportDM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('read', models.BooleanField(default=False, verbose_name='既読')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('userReceive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportDM_receive', to='CCapp.User', verbose_name='受信者ID')),
                ('userSend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportDM_send', to='CCapp.User', verbose_name='送信者ID')),
            ],
            options={
                'verbose_name': 'サポートDM',
                'db_table': 'supportDM',
            },
        ),
        migrations.CreateModel(
            name='Question01',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('question00', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question01_question00', to='CCapp.Question00', verbose_name='質問00')),
            ],
            options={
                'verbose_name': '質問01',
                'db_table': 'question01',
            },
        ),
        migrations.CreateModel(
            name='OfferEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerApp_offer', to='CCapp.Offer', verbose_name='求人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerApp_user', to='CCapp.User', verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': '求人',
                'db_table': 'offer',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='applicants',
            field=models.ManyToManyField(related_name='offer_offerEntry', through='CCapp.OfferEntry', to='CCapp.User', verbose_name='応募者リスト'),
        ),
        migrations.AddField(
            model_name='offer',
            name='area1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_area1', to='CCapp.Area1', verbose_name='エリア1'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category00',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_category00', to='CCapp.Category00', verbose_name='カテゴリ00'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category01',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_category01', to='CCapp.Category01', verbose_name='カテゴリ01'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category10',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_category10', to='CCapp.Category10', verbose_name='カテゴリ10'),
        ),
        migrations.AddField(
            model_name='offer',
            name='category11',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_category11', to='CCapp.Category11', verbose_name='カテゴリ11'),
        ),
        migrations.AddField(
            model_name='offer',
            name='corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CCapp.Corporation', verbose_name='法人'),
        ),
        migrations.AddField(
            model_name='offer',
            name='welfare',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CCapp.Tag', verbose_name='福利厚生'),
        ),
        migrations.CreateModel(
            name='DM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('read', models.BooleanField(default=False, verbose_name='既読')),
                ('detail', models.TextField(verbose_name='詳細')),
                ('corp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCapp.Corporation', verbose_name='法人番号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CCapp.User', verbose_name='ユーザID')),
            ],
            options={
                'verbose_name': 'DM',
                'db_table': 'DM',
            },
        ),
        migrations.CreateModel(
            name='Area2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('area1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area2_area1', to='CCapp.Area1', verbose_name='エリア1')),
            ],
            options={
                'verbose_name': 'エリア2',
                'db_table': 'Area2',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='CCapp.User', verbose_name='ユーザID')),
                ('furigana', models.CharField(max_length=256, verbose_name='フリガナ')),
                ('nationality', models.CharField(max_length=256, verbose_name='国籍')),
                ('birth', models.DateField(verbose_name='生年月日')),
                ('gender', models.CharField(max_length=16, verbose_name='性別')),
                ('graduation', models.IntegerField(verbose_name='卒業年度')),
                ('uSchool', models.CharField(max_length=256, verbose_name='学校名')),
                ('sClass', models.IntegerField(verbose_name='学校区分')),
                ('sol', models.IntegerField(verbose_name='文理区分')),
                ('department', models.CharField(max_length=32, verbose_name='学科名')),
                ('uTel', models.CharField(max_length=16, verbose_name='電話番号')),
                ('postalCode', models.CharField(max_length=8, verbose_name='郵便番号')),
                ('uAddress', models.CharField(max_length=256, verbose_name='住所')),
                ('uOffer', models.CharField(max_length=256, verbose_name='内定先')),
                ('area1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_area1', to='CCapp.Area1', verbose_name='エリア1')),
                ('category00', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_category00', to='CCapp.Category00', verbose_name='カテゴリ00')),
                ('category01', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_category01', to='CCapp.Category01', verbose_name='カテゴリ01')),
                ('category10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_category10', to='CCapp.Category10', verbose_name='カテゴリ10')),
                ('category11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_category11', to='CCapp.Category11', verbose_name='カテゴリ11')),
            ],
            options={
                'verbose_name': 'プロフィール',
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='CCapp.User', verbose_name='ユーザID')),
                ('response', models.TextField(verbose_name='回答')),
                ('question01', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_question01', to='CCapp.Question01', verbose_name='質問')),
            ],
            options={
                'verbose_name': '自己分析',
                'db_table': 'assessment',
            },
        ),
    ]
