# Generated by Django 5.1.2 on 2025-01-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='プロフィール写真'),
        ),
    ]
